---
title: "Minimal COVID-19 dashboard"
author: "Martin Chan"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<style>                     
.navbar {
  background-color:#363636;
  
}
</style>   
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Methodology
=====================================

Column {data-width=300}
-----------------------------------------------------------------------

### Background

```{r message=FALSE, warning=FALSE, include=FALSE}  
#### Load packages ####
library(tidyverse)
library(flexdashboard)

#### Load datasets ####
df_confirmed <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
df_deaths <- read_csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv")
df_recovered <- read_csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv")

run_summary <- function(data, varname){
  data %>%
    select(-`Province/State`, -`Country/Region`, -Lat, -Long) %>%
    gather(Date, !!sym(varname)) %>%
    group_by(Date) %>%
    summarise(!!sym(varname) := sum(!!sym(varname)))
}

df_confirmed %>% run_summary(varname = "Confirms") -> summary_confirmed
df_deaths %>% run_summary(varname = "Deaths") -> summary_deaths
df_recovered %>% run_summary(varname = "Recovered") -> summary_recovered

list(summary_confirmed,
     summary_deaths,
     summary_recovered) %>%
  reduce(full_join, by = "Date") %>%
  mutate(N_Outcome = Deaths + Recovered) %>%
  mutate(FatalityRate = Deaths / N_Outcome) %>%
  mutate_at(vars(Date), ~lubridate::mdy(.)) -> output_data
```

Column {data-width=500} {.tabset}
-----------------------------------------------------------------------

### Fatality Rate

```{r echo=FALSE}
output_data %>%
  ggplot(aes(x = Date, y = FatalityRate)) +
  geom_line()
```

