---
title: "Minimal COVID-19 dashboard"
author: "Martin Chan"
output: 
  flexdashboard::flex_dashboard:
    theme: cosmo
    orientation: columns
    vertical_layout: fill
---

<style>                     
.navbar {
  background-color:#363636;
  
}
</style>   
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dashboard
=====================================

Column {data-width=300}
-----------------------------------------------------------------------

### Background

Minimal COVID-19 (novel coronavirus) dashboard built using RMarkdown and flexdashboard

This is a minimal prototype to build COVID-19 dashboard using the {RMarkdown} and {flexdashboard} packages.

The data used to build the analysis is taken from the data repository for the 2019 Novel Coronavirus Visual Dashboard, operated by the Johns Hopkins University Center for Systems Science and Engineering (JHU CCSE). Their GitHub repo is linked [here](https://github.com/CSSEGISandData/COVID-19).

```{r message=FALSE, warning=FALSE, include=FALSE}  
#### Load packages ####
library(tidyverse)
library(flexdashboard)
library(dygraphs)
library(timetk)
library(here)

#### Load functions ####
source(here("Script", "Functions", "create_dt.R"))
source(here("Script", "Functions", "rgb2hex.R"))

#### Load datasets ####
df_confirmed <- read_csv("https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Confirmed.csv")
df_deaths <- read_csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Deaths.csv")
df_recovered <- read_csv("https://github.com/CSSEGISandData/COVID-19/raw/master/csse_covid_19_data/csse_covid_19_time_series/time_series_19-covid-Recovered.csv")

run_summary <- function(data, varname){
  data %>%
    select(-`Province/State`, -`Country/Region`, -Lat, -Long) %>%
    gather(Date, !!sym(varname)) %>%
    group_by(Date) %>%
    summarise(!!sym(varname) := sum(!!sym(varname)))
}

df_confirmed %>% run_summary(varname = "Confirms") -> summary_confirmed
df_deaths %>% run_summary(varname = "Deaths") -> summary_deaths
df_recovered %>% run_summary(varname = "Recovered") -> summary_recovered

list(summary_confirmed,
     summary_deaths,
     summary_recovered) %>%
  reduce(full_join, by = "Date") %>%
  mutate(N_Outcome = Deaths + Recovered) %>%
  mutate(FatalityRate = Deaths / N_Outcome) %>%
  mutate_at(vars(Date), ~lubridate::mdy(.)) -> output_data
```

Column {data-width=500} {.tabset}
-----------------------------------------------------------------------

### Fatality Rate

```{r echo=FALSE}
output_data %>%
  # ggplot(aes(x = Date, y = FatalityRate)) +
  # geom_line()
  timetk::tk_xts(select = c(N_Outcome, FatalityRate),
                 date_var = Date) %>%
  dygraph(main = "Outcomes and Fatality Rate") %>%
  dyAxis("y", label = "Fatality Rate") %>%
  dyAxis("y2", label = "Number of Confirmed Cases with Outcomes", independentTicks = TRUE) %>%
  dyAxis("x", label = "Date") %>%
  dySeries("N_Outcome", axis = "y2") %>%
  dyRangeSelector() %>%
  dyOptions(colors = c(rgb2hex(65,75,170),rgb2hex(128,128,128)),
            drawGrid = FALSE, fillGraph = TRUE) %>%
  dyHighlight(highlightCircleSize = 5,
              highlightSeriesBackgroundAlpha = 0.2,
              hideOnMouseOut = TRUE)
```

### Table

```{r echo=FALSE}
output_data %>%
  arrange(Date) %>%
  create_dt() %>%
  DT::formatPercentage(c("FatalityRate"), 1)
```
